# Generated by Django 4.1 on 2023-12-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.CharField(max_length=100, null=True)),
                ('option_one', models.CharField(max_length=50, null=True)),
                ('option_two', models.CharField(max_length=50, null=True)),
                ('option_three', models.CharField(max_length=50, null=True)),
                ('option_four', models.CharField(max_length=50, null=True)),
                ('votes_one', models.IntegerField(default=0)),
                ('votes_two', models.IntegerField(default=0)),
                ('votes_three', models.IntegerField(default=0)),
                ('votes_four', models.IntegerField(default=0)),
            ],
        ),
    ]
